### PR TITLE
Examples added

### LINKED ISSUE #187: Examples are out of date
No `runtime` package in `dpctl`.

/CC @densmirn

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Closes #187 

This PR reorganizes `examples/` folder.  The current structure is as follows:

```
(idp) [14:14:25 ansatnuc04 examples]$ tree .
.
├── cython
│   ├── sycl_buffer
│   │   ├── bench.py
│   │   ├── _buffer_example.pyx
│   │   ├── README.md
│   │   ├── run.py
│   │   ├── setup.py
│   │   ├── use_sycl_buffer.cpp
│   │   └── use_sycl_buffer.h
│   ├── sycl_direct_linkage
│   │   ├── _buffer_example.pyx
│   │   ├── run.py
│   │   ├── setup.py
│   │   ├── sycl_function.cpp
│   │   └── sycl_function.hpp
│   └── usm_memory
│       ├── blackscholes.pyx
│       ├── README.md
│       ├── reference_black_scholes.py
│       ├── run.py
│       ├── setup.py
│       ├── sycl_blackscholes.cpp
│       └── sycl_blackscholes.hpp
└── python
    ├── create_sycl_queues.py
    ├── usm_memory_allocation.py
    ├── usm_memory_host_access.py
    └── usm_memory_operation.py

5 directories, 23 files
```

Examples in `python/` folder intend to show usage of `dpctl` from Python. Perhaps this folder may also showcase usage of `ctypes` to interface with `DPPLSyclInterface` shared library.

Examples in `cython/` folder intend to provide examples of building Cython extensions using `dpctl`.

Forthcoming examples will show `pybind11` as well as SWIG, which will go in their respective folders.

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
Is it possible to create makefile for building Cython examples?

**Comment by diptorupd** [comment]
> 
> 
> Is it possible to create makefile for building Cython examples?

We can add an optional cmake option to build the examples? Should we also add examples for the C API in this folder?

**Comment by oleksandr-pavlyk** [comment]
Each example can be built using `CXX=dpcpp CC=clang python setup.py develop`. This is reflected in README.md

**Comment by PokhodenkoSA** [comment]
@diptorupd
I think we can check examples in this PR manually. Creating build scripts and CI should be in separate PR.

**Comment by PokhodenkoSA** [comment]
@oleksandr-pavlyk Could you please update main README.md section Examples too?

**Review by PokhodenkoSA — CHANGES_REQUESTED** [review]
Could you please update [main README.md section Examples](https://github.com/IntelPython/dpctl/tree/examples-added#examples) too?

**Comment by diptorupd** [comment]
Merging, as this is a big improvement over what we have currently.

**Pull request merged**
