### PR TITLE
Depend on the source headers directly

### PR DESCRIPTION
**Pull request by ZzEeKkAa**
Update CMake configuration and headers to  use better target dependencies. It will unblock incremental compilation and flexible dependency management.

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
Increase in coverage is due to disappearence of Cython files from coverage.

**Comment by oleksandr-pavlyk** [comment]
gh-1586 does not exhibit changes in coverage metrics despite also using Cython 3.0.9. 

I also checked that C++ code generated by Cython did not materially change between versions.

Thus the change is caused by build system reorg.

**Comment by oleksandr-pavlyk** [comment]
This message emitted while processing `.coverage` database points to a problem:

```
Source file is not python /home/runner/work/dpctl/dpctl/dpctl/_diagnostics.pyx
```

**Comment by ZzEeKkAa** [comment]
May it be because we don't copy headers/cpp files of cython to source directory and they are always in build directory now?

**Comment by oleksandr-pavlyk** [comment]
> May it be because we don't copy headers/cpp files of cython to source directory and they are always in build directory now?

Yes, indeed. See http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html

I have pushed changes to copy CXX files into layout for coverage builds.

**Review by oleksandr-pavlyk — APPROVED** [review]
Thank you for getting this done @ZzEeKkAa ! Looks good to me now!

**Comment by oleksandr-pavlyk** [comment]
Testing clean building with and without use of `lld`, using

```bash
/usr/bin/time -f "%P %M %E" python scripts/build_locally.py --verbose
```

outputs are, on my WSL machine,

```
with lld
641% 3953024 20:24.33

with default linker
632% 4048804 20:59.47
```

**Review by ndgrigorian — APPROVED** [review]
I have also tested building this branch locally and it LGTM

**Comment by oleksandr-pavlyk** [comment]
I have checked locally that `dpnp` build continues working as expected.

**Comment by antonwolfy** [comment]
I can also confirm that `dpnp` build works with that PR without any issue.

**Review by antonwolfy — APPROVED** [review]

**Pull request merged**
