### PR TITLE
Feature/code style automation

### PR DESCRIPTION
**Pull request by diptorupd**
Various changes to code style tooling:

1. `flake8`, `isort` jobs added to check for Python code style for new PRs against `master`, `gold/2021`, `release` branches.
2. `black` max line width changed to 80 chars.
3. `flake8` and `isort` configs added.
4. `pre-commit` hooks added to make it possible to run all these checks prior to pushing code.
5. `CONTRIBUTION.md` updated.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
It is imperative that source code passes all the linter checks before this effort is merged. 

My attempt to take this for a ride revealed black auto-formats some code that flake8 flags, example of it being 

```python 
__all__ = (a
   + b 
   + c
   + d )
```

Flake8 runs on Cython files, and flags legal Cython extensions of Python as syntactic errors.

**Comment by diptorupd** [comment]
> It is imperative that source code passes all the linter checks before this effort is merged.
> 
> My attempt to take this for a ride revealed black auto-formats some code that flake8 flags, example of it being
> 
> ```python
> __all__ = (a
>    + b 
>    + c
>    + d )
> ```
> 
> Flake8 runs on Cython files, and flags legal Cython extensions of Python as syntactic errors.

The [black docs](https://black.readthedocs.io/en/stable/compatible_configs.html#flake8) point out to this possibility and provide a flake config option. I have added the exception to the `.flake` file.

**Comment by PokhodenkoSA** [comment]
@diptorupd I know that muting warnings fixes CI. I would prefer the following way: run checks locally. Find most danger warnings. Fix in separate PRs and the apply this PR.

**Comment by PokhodenkoSA** [comment]
> Fix in separate PRs and the apply this PR.

It will split CI changes from fixes.

**Comment by diptorupd** [comment]
> > Fix in separate PRs and the apply this PR.
> 
> It will split CI changes from fixes and code improvements.



> It will split CI changes from fixes and code improvements.

Yes, #416 has the fixes. I just rebased #416 on top of this PR to see the results. Ultimately, I will merge #416 separately and this PR will have only the code improvement checks here.

**Pull request closed without merging**
