### PR TITLE
`divide` and comparisons allow a greater range of Python integer and integer array combinations

### LINKED ISSUE #1711: Unexpected result from divide-like ufuncs with unsigned integer array and negative integer scalar as inputs
The below example demonstrates unexpected dpctl behavior for `divide`, `floor_divide` and `remainder` binary functions.
The issue is visible when one of the input has unsinged integer type, while another input is negative integer scalar.

Here is an example for `divide`:
```python
import numpy, dpctl, dpctl.tensor as dpt

dpctl.__version__
# Out: '0.18.0dev0+73.gc81735a928'

dpt.divide(dpt.asarray(3, dtype='u4'), -2)
# Out: usm_ndarray(6.9849193e-10, dtype=float32)

numpy.divide(numpy.asarray(3, dtype='u4'), -2)
# Out: -1.5

dpt.divide(-4, dpt.asarray(3, dtype='u4'))
# Out: usm_ndarray(1.4316558e+09, dtype=float32)

numpy.divide(-4, numpy.asarray(3, dtype='u4'))
# Out: -1.3333333333333333
```
similar with `floor_divide`:
```python
dpt.floor_divide(dpt.asarray(7, dtype='u4'), -2)
# Out: usm_ndarray(0, dtype=uint32)

numpy.floor_divide(numpy.asarray(7, dtype='u4'), -2)
# Out: -4
```
and `remainder`:
```python
dpt.remainder(dpt.asarray(7, dtype='u4'), -2)
# Out: usm_ndarray(7, dtype=uint32)

numpy.remainder(numpy.asarray(7, dtype='u4'), -2)
# Out: -1
```

### PR DESCRIPTION
**Pull request by ndgrigorian**
This PR closes #1711 by aligning `divide` with Numpy 2.0 behavior.

When a Python integer is out-of-bounds for a (strong, array) integer data type of the other input, `_resolve_weak_types_all_py_ints` uses `np.min_scalar_type` to find the minimum type that will fit it.

This does not affect the output type of comparisons or `divide`, and therefore aligns with NEP-50 while permitting such workflows as:

```
In [2]: dpt.divide(-4, dpt.asarray(3, dtype="u4"))
Out[2]: usm_ndarray(-1.3333334, dtype=float32)
```

This also fixes a bug introduced in #1650 where comparisons between `uint64` data type arrays and Python integers larger than the maximum for the default integral data type no longer worked.

- [X] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [X] Have you tested your changes locally for CPU and GPU devices?
- [X] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [X] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
This example from gh-1711 still give unexpected result:

```
In [4]: dpt.floor_divide(dpt.asarray(7, dtype='u4'), -2)
Out[4]: usm_ndarray(0, dtype=uint32)
```

**Comment by ndgrigorian** [comment]
> This example from [gh-1711](https://github.com/IntelPython/dpctl/issues/1711) still give unexpected result:
> 
> ```
> In [4]: dpt.floor_divide(dpt.asarray(7, dtype='u4'), -2)
> Out[4]: usm_ndarray(0, dtype=uint32)
> ```

It won't after Numpy 2, because -2 will no longer be permitted to promote to uint32.

In general it may be a good idea to go back and disallow overflows from Python integers in `asarray` explicitly, just as Numpy has done.

**Comment by oleksandr-pavlyk** [comment]
Indeed, with NumPy 2.0 in run-time environment, I am getting 

```
OverflowError: Python integer -2 out of bounds for uint32
```

**Review by oleksandr-pavlyk — APPROVED** [review]
Thank you @ndgrigorian ! LGTM

**Pull request merged**
