### PR TITLE
Roll must reduce shift steps by size along axis

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Closes gh-1857

Test added based on example provided in the issue.

- [x] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to an issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [x] Have you checked performance impact of proposed changes?
- [ ] Have you added documentation for your changes, if necessary?
- [ ] Have you added your changes to the changelog?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Review by ndgrigorian — COMMENTED** [review]
This change seems to have introduced a failure in an array API test

**Comment by oleksandr-pavlyk** [comment]
> This change seems to have introduced a failure in an array API test

I have pushed a fix to this issue, and added tests to cover it.

**Comment by oleksandr-pavlyk** [comment]
Interestingly, I can not reproduce this issue in AWS, neither running an individual test file:

```
(dev_dpctl) ubuntu@ip-172-31-15-142:~/repos/dpctl$ python -m pytest dpctl/tests/test_usm_ndarray_manipulation.py
============================================================================ test session starts ============================================================================
platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/ubuntu/repos/dpctl
configfile: pyproject.toml
collected 266 items

dpctl/tests/test_usm_ndarray_manipulation.py ........................................................................................................................ [ 45%]
..................................................................................................................................................                    [100%]

============================================================================ 266 passed in 4.07s ============================================================================
(dev_dpctl) ubuntu@ip-172-31-15-142:~/repos/dpctl$ sycl-ls
[opencl:cpu][opencl:0] Intel(R) OpenCL, AMD EPYC 7R32 OpenCL 3.0 (Build 0) [2024.18.7.0.11_160000]
(dev_dpctl) ubuntu@ip-172-31-15-142:~/repos/dpctl$ git status
On branch bugfix/gh-1857-roll-with-large-shift
Your branch is up to date with 'origin/bugfix/gh-1857-roll-with-large-shift'.

nothing to commit, working tree clean
```

nor running the entire test suite:

```
dpctl/tests/test_utils.py .......                                                                                                                                     [100%]

======================================================== 15852 passed, 1896 skipped, 1 xfailed in 472.32s (0:07:52) =========================================================
(dev_dpctl) ubuntu@ip-172-31-15-142:~/repos/dpctl$
```

**Comment by oleksandr-pavlyk** [comment]
Also created test environment from the artifact built by `build_linux` step of the workflow, and the entire test suite passed in AWS.

**Review by ndgrigorian — APPROVED** [review]
I've tested this change out and it seems to be working as expected.

The tests could include one with a very large (in magnitude) negative number but I don't think it's necessary. I did test that case out and it worked as expected too.

LGTM!

**Review by antonwolfy — APPROVED** [review]
Thank you for resolving the issue @oleksandr-pavlyk

**Pull request merged**
