### PR TITLE
DPCTLQueue_Memcpy, _Prefetch, _Memadvise become asynchronous

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
The return value of these functions changed. Declaration, documentation,
tests and implementations updated in dpctl-capi/.

dpctl/_backend.pxd updated for changed return type. Usages updated
accordingly to get the event and wait on it to preserve the behavior
for now.

### CODE REVIEW

**Review by PokhodenkoSA — APPROVED** [review]
LGTM

**Comment by adarshyoga** [comment]
Does this change need an update/addition to test cases?

**Comment by oleksandr-pavlyk** [comment]
> Does this change need an update/addition to test cases?

The only change that was needed is in `dpctl-capi/tests` and was made in this PR. The Python semantics did not change, Python calls remain synchronous. We just replaced previous calls `DPCTLQueue_Memcpy(QRef, dst_ptr, src_ptr, num_bytes)` with 

```c
   ERef = DPCTLQueue_Memcpy(QRef, dst_ptr, src_ptr, num_bytes)
   DPCTLEvent_Wait(ERef)
   DPCTLEvent_Delete(ERef)
```

**Review by adarshyoga — APPROVED** [review]

**Review by PokhodenkoSA — APPROVED** [review]

**Comment by oleksandr-pavlyk** [comment]
@reazulhoque Is this change ok to merge?

**Comment by reazulhoque** [comment]
Not yet. I am still getting segfaults when testing Numba-dppy with dpnp.

**Comment by reazulhoque** [comment]
I am using Numba-dppy master and testing locally. This is a matter of updating dpnp glue implementations in Numba-dppy to wait for the memcpy event.

**Comment by reazulhoque** [comment]
Locally all tests passed. Created PR in Numba-dppy https://github.com/IntelPython/numba-dppy/pull/529

**Review by reazulhoque — APPROVED** [review]

**Pull request merged**
