### PR TITLE
Feature/build with scikit build and cmake

### LINKED ISSUE #743: Use oneAPI's IntelDPCPPConfig.cmake
Instead of custom `FindIntelSycl.cmake` we could use/reuse oneAPI's config module, located in `${ONEAPI_ROOT}/compiler/latest/linux/IntelDPCPP/IntelDPCPPConfig.cmake` (on Linux machines).

### LINKED ISSUE #747: Move build system to CMake + skbuild
The assortment of remaining tasks to complete transition of DCPTL to cmake + skbuild.

- [x] Enable `sycl::program` in `libsyclinterface/tests/dpcpp_kernels.hpp`.
- [x] Add build system configuration to pyproject.toml (e.g. specify dependencies for building docs).
- [x] cmake + skbuild should work with nightly sycl bundles
- [x] Write coverage build driver (`scripts/gen_coverage.py`)
- [ ] Write docs driver (`scripts/gen_docs.py`)
- [x] Write script to drive build with sycl nightly
- [x] Ensure SDL flags are added to `CMakeLists.txt`
- [x] Upstream change to skbuild to preserve symbolic link to components of versioned shared library 
- [x] Fix #651, make sure versioneer overrides `dpctl/_version.py`, a step which relies on using versioneer provided "build_py" step.  
- [ ] Make sure pybind11 extension can be added to `dpctl`, which is the ultimate reason for this work

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Closes #747 
Closes #743 

This is PR transition `dpctl` to use scikit-build project to control building both libsyclinterface and python extensions via CMake. Minimum required Cmake version [is 3.21](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-setup/using-the-command-line/using-cmake-with-data-parallel-c-dpc.html) to support `find_package(IntelDPCPP REQUIRED)`. 

DPC++ is now being used to build both the library and the Python API compoenents.

To build in develop, use

```sh
python setup.py develop -- -G "Unix Makefiles" -- -DCMAKE_CXX_COMPILER:PATH=icpx  -DDPCTL_ENABLE_LO_PROGRAM_CREATION=ON
```

Alternatively one can use driver scripts:

```sh
python scripts/build_sycl_nightly.py --oneapi
```

Previous syntax of using `--sycl-compiler-prefix` will no longer work.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
I am going to defer writing `scripts/gen_docs.py` to another PR. One can use `python scripts/build_sycl_nightly.py --oneapi` to build develop.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Thanks for the much needed changes. Can you please update the PR description with a list of changes that were done in the PR. Also, please review the commits to see if any need squashing (such as any WIP commits). Overall, let us merge the and move forth asap.

**Comment by diptorupd** [comment]
Is the `FindIntelSycl` module still needed?

**Comment by oleksandr-pavlyk** [comment]
> Is the `FindIntelSycl` module still needed?

One can probably do away with it, but that is additional work which belongs to a separate PR.

More likely we need to streamline it to reuse what is computed in `IntelDPCPPConfig.cmake`.

**Comment by oleksandr-pavlyk** [comment]
> @oleksandr-pavlyk Thanks for the much needed changes. Can you please update the PR description with a list of changes that were done in the PR? Also, please review the commits to see if any need squashing (such as any WIP commits). Overall, let us merge the and move forth asap.

I have rebased and squashed several commits. Ready for rereview.

**Pull request merged**
