### PR TITLE
Implemented advanced indexing kernels (take, put)

### PR DESCRIPTION
**Pull request by ndgrigorian**
- Kernels for _take, _put
- Python API functions for take, put

Replaced mock functions for testing purposes
Currently passes tests in test_usm_ndarray_indexing.py
More tests to come

- [ ] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?

### CODE REVIEW

**Comment by diptorupd** [comment]
> This change has brought coverage down significantly, from 82.3% to 80.71%. For some reason the app has not posted a comment with this statistics

Not sure why the statistics are not posted. 

If you want to flag the drop in coverage to trigger a `coverage/coveralls` step failure, then we will need to change the threshold in coveralls.io. The threshold was set to 5% drop when we originally set up the job. If you want, I can change it to a lesser threshold that will capture coverage decrease as a failed step in CI.

**Comment by npolina4** [comment]
Wrong result. Should the function return an error like in Numpy?

``` python
>>> a = dpt.arange(24)
>>> a = dpt.reshape(a, (4,6))
>>> dpt.take(a, dpt.asarray(3), axis=0)
usm_ndarray([18, 19, 20, 21, 22, 23])
>>> dpt.take(a, dpt.asarray(4), axis=0)
usm_ndarray([18, 19, 20, 21, 22, 23])

>>> a_np = numpy.arange(24).reshape((4, 6))
>>> numpy.take(a_np, 4, axis=0)
IndexError: index 4 is out of bounds for axis 0 with size 4
```

**Comment by ndgrigorian** [comment]
> Wrong result. Should the function return an error like in Numpy?
> 
> ```python
> >>> a = dpt.arange(24)
> >>> a = dpt.reshape(a, (4,6))
> >>> dpt.take(a, dpt.asarray(3), axis=0)
> usm_ndarray([18, 19, 20, 21, 22, 23])
> >>> dpt.take(a, dpt.asarray(4), axis=0)
> usm_ndarray([18, 19, 20, 21, 22, 23])
> 
> >>> a_np = numpy.arange(24).reshape((4, 6))
> >>> numpy.take(a_np, 4, axis=0)
> IndexError: index 4 is out of bounds for axis 0 with size 4
> ```

No, because we can't raise exceptions in the kernels without crashing the program, currently advanced indices don't raise an error and default to clipping.

Raising an error may be added with a reduction in the future, but clipping is more performant.

**Comment by oleksandr-pavlyk** [comment]
:+1!

**Pull request merged**
