### PR TITLE
Doc improvement

### PR DESCRIPTION
**Pull request by diptorupd**
Various improvements to dpctl documentation website. 
 - We now use doxyrest to generate C API docs.
 - A new QuickStart guide
 - Reorganizing the docs directory
 - Change existing file names.

### CODE REVIEW

**Comment by diptorupd** [comment]
> 
> 
> What's the command for rendering the docs?

In the README :)

**Comment by oleksandr-pavlyk** [comment]
Is this PR overlapping with #342 ?

**Comment by diptorupd** [comment]
> 
> 
> Is this PR overlapping with #342 ?

I cherry picked 7adf12449c9901e82cd32efeaa4c68fa100be0a8 out to reduce the shear number of files being changed in this PR.

**Comment by oleksandr-pavlyk** [comment]
You have to merge the master into this branch to see that reduction, I suppose.

**Comment by oleksandr-pavlyk** [comment]
I installed doxyrest from conda-forge `conda install conda-forge::doxyrest`. 

These errors seem like a problem with our sources.

```
Generating group documentation...
/localdisk/work/opavlyk/repos/dpctl/dpctl-capi/include/dpctl_sycl_device_manager.h:46: warning: argument 'VRef' of command @param is not found in the argument list of DPCTL
DeviceVector_Delete(DPCTLDeviceVectorRef Ref)
/localdisk/work/opavlyk/repos/dpctl/dpctl-capi/include/dpctl_sycl_device_manager.h:46: warning: The following parameter of DPCTLDeviceVector_Delete(DPCTLDeviceVectorRef Ref
) is not documented:
  parameter 'Ref'
/localdisk/work/opavlyk/repos/dpctl/dpctl-capi/include/dpctl_sycl_platform_manager.h:44: warning: argument 'VRef' of command @param is not found in the argument list of DPC
TLPlatformVector_Delete(DPCTLPlatformVectorRef Ref)
/localdisk/work/opavlyk/repos/dpctl/dpctl-capi/include/dpctl_sycl_platform_manager.h:44: warning: The following parameter of DPCTLPlatformVector_Delete(DPCTLPlatformVectorR
ef Ref) is not documented:
  parameter 'Ref'
```

**Comment by oleksandr-pavlyk** [comment]
I merge master into this branch, resolved conflicts and modified include/dpctl_vector.h to take care of quoted warnings. 

This is pushed to https://github.com/IntelPython/dpctl/pull/new/review-of-doc-improvement

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I just bit the bullet and published the WIP docs. The do not seem to have rendered yet or there is some issue.

The latest site is at : https://intelpython.github.io/dpctl/latest/index.html
0.6.1: https://intelpython.github.io/dpctl/0.6.1/index.html

**Review by oleksandr-pavlyk — APPROVED** [review]

**Comment by diptorupd** [comment]
Closing in favour of #397

**Pull request closed without merging**
