### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by 1e-to**

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
@diptorupd in this PR @1e-to started CHANGELOG file. It is impossible for her to collect all information you have. Could you check existing file and fill it with more actual information using proposed format?

**Review by PokhodenkoSA — APPROVED** [review]
LGTM for the starting point.

**Review by diptorupd — APPROVED** [review]
Looks good. Can we add the bullet points that I added to 3.5 release notes? For older tags, I review what Elena has put in and it looks fine for now.

**Comment by diptorupd** [comment]
LGTM. Thanks @1e-to!

**Pull request merged**
