### PR TITLE
Require numpy 2 at build time

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Change `pyproject.toml` to require `numpy>=2.0` for building `dpctl`.

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [x] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by ekomarova** [comment]
It looks like there are conflicts in internal CI when using numpy from conda-forge
```
 The following package could not be installed
└─ numpy 2.0.0  is not installable because it conflicts with any installable versions previously reported.
```

**Comment by ekomarova** [comment]
I think the reason is mkl:
```
>conda create -n numpy_v2 numpy=2.0.0 -c conda-forge

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    intel-openmp-2024.2.0      |     h57928b3_980         1.8 MB  conda-forge
    libblas-3.9.0              |     23_win64_mkl         5.0 MB  conda-forge
    libcblas-3.9.0             |     23_win64_mkl         5.0 MB  conda-forge
    libhwloc-2.11.1            |default_h8125262_1000         2.3 MB  conda-forge
    liblapack-3.9.0            |     23_win64_mkl         5.0 MB  conda-forge
    libxml2-2.12.7             |       h0f24e4e_4         1.6 MB  conda-forge
    mkl-2024.1.0               |     h66d3029_694       104.3 MB  conda-forge
    numpy-2.0.0                |  py312h49bc9c5_0         6.7 MB  conda-forge
    python-3.12.4              |h889d299_0_cpython        15.4 MB  conda-forge
    tbb-2021.12.0              |       hc790b64_3         157 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       147.1 MB

>conda search mkl=2024.1.0=h66d3029_694 -i -c conda-forge
Loading channels: done
mkl 2024.1.0 h66d3029_694
-------------------------
file name   : mkl-2024.1.0-h66d3029_694.conda
name        : mkl
version     : 2024.1.0
build       : h66d3029_694
build number: 694
size        : 104.3 MB
license     : LicenseRef-IntelSimplifiedSoftwareOct2022
subdir      : win-64
url         : https://conda.anaconda.org/conda-forge/win-64/mkl-2024.1.0-h66d3029_694.conda
md5         : a17423859d3fb912c8f2e9797603ddb6
timestamp   : 2024-05-24 14:36:14 UTC
dependencies:
  - intel-openmp 2024.*
  - tbb 2021.*
```
This environment is incompatible with 2025 compiler

**Comment by oleksandr-pavlyk** [comment]
@ekomarova I think we should merge this PR, since it is being merged into another branch, not in the main branch.

**Comment by ekomarova** [comment]
I would not add a restriction for numpy, and would just leave `"numpy",` in pyproject.toml instead of `"numpy >=1.23"` in order to be able to set the numpy version in the build cmd, and not through the recipe.

**Comment by ekomarova** [comment]
We have also already built numpy 2.0.1 for linux and I think we will finish with windows soon

**Comment by oleksandr-pavlyk** [comment]
Ok, let keep this one open until NumPy 2.0.1 is available in the internal CI for all platforms, and the target branch of this PR could be built without this change.

**Comment by oleksandr-pavlyk** [comment]
This is not the right change, so closing this PR.

**Pull request closed without merging**
