### PR TITLE
Implements `dpctl.tensor.put_along_axis`

### PR DESCRIPTION
**Pull request by ndgrigorian**
This PR leverages the index-building function `_range` used in `take_along_axis` to implement `dpctl.tensor.put_along_axis`.

- [X] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to an issue with a reproducer?
- [X] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [x] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
The `append` at line 236 should probably be removed too.

**Comment by oleksandr-pavlyk** [comment]
I am afraid the line "See :func:`dpctl.tensor.put` for an example." may be confusing. The `indices` in `put_along_axis` is a regular array of the same rank as the input, but in the presence of duplicate indices, we may have different number of unique indices, and the array of unique indices may be ragged (more of a list of lists of different lengths). 

I would only leave the note.

**Comment by ndgrigorian** [comment]
> I am afraid the line "See :func:`dpctl.tensor.put` for an example." may be confusing. The `indices` in `put_along_axis` is a regular array of the same rank as the input, but in the presence of duplicate indices, we may have different number of unique indices, and the array of unique indices may be ragged (more of a list of lists of different lengths).
> 
> I would only leave the note.

Good point! I'll remove it. It might be nice to show an example for this case separately.

**Comment by oleksandr-pavlyk** [comment]
The implementation looks good! Tests are needed to avoid the drop in coverage

**Review by oleksandr-pavlyk — APPROVED** [review]
I have added tests for `put_along_axis`. Changes now increase coverage. 

Thank you for implementing `put_along_axis` @ndgrigorian ! Looks good to me

**Review by oleksandr-pavlyk — APPROVED** [review]
@ndgrigorian I think GH expects  you to review changes I pushed and approve before it would unblock merging without admin override.

**Comment by ndgrigorian** [comment]
@oleksandr-pavlyk 
I just realized that it's not in the docs, I'll push a commit to add `put_along_axis` there, then you will have to approve again and we can merge it. Thanks for adding tests!

**Review by oleksandr-pavlyk — APPROVED** [review]

**Pull request merged**
