### PR TITLE
Review sub devices

### LINKED ISSUE #290: Implement support for sub-devices
Implement support for sub-devices. SYCL has three create_sub_devices functions and we should support all three:
- [ ] DPCTLDevice_CreateSubDevicesEqually
- [ ] DPCTLDevice_CreateSubDevicesByCounts
- [ ] DPCTLDevice_CreateSubDevicesByAffinityDomain

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Closes #290 

Changes were added atop commits in #326, and this PR superseded #326.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
This supersedes #326 now to expedite merging of this work to master.

@1e-to @diptorupd @PokhodenkoSA

**Comment by diptorupd** [comment]
> This supersedes #326 now to expedite merging of this work to master.
> 
> @1e-to @diptorupd @PokhodenkoSA

@oleksandr-pavlyk @PokhodenkoSA @1e-to As-is this PR cannot be merged into master. It has work-in-progress commits with temporary commit messages that I will not merge into master. While we are still a very small beta library it can catch up soon. I want us to stick to something close to (if not as stringent as https://releases.llvm.org/8.0.1/docs/DeveloperPolicy.html#incremental-development). Thoughts?

**Comment by diptorupd** [comment]
> As-is this PR cannot be merged into master.

I am making the comment after trying to and giving up on cleaning up using interactive rebase, but that is a huge drag on my time.

**Comment by diptorupd** [comment]
> > As-is this PR cannot be merged into master.
> 
> I am making the comment after trying to and giving up on cleaning up using interactive rebase, doing such a rebase is a huge drag on my time.

@oleksandr-pavlyk I cleaned up and squashed the temporary patches and have opened a new PR. Let us review and merge that one.

**Comment by diptorupd** [comment]
Thanks @oleksandr-pavlyk for an excellent display of git-fu.

**Comment by oleksandr-pavlyk** [comment]
> > As-is this PR cannot be merged into master.
> 
> I am making the comment after trying to and giving up on cleaning up using interactive rebase, doing such a rebase is a huge drag on my time.

We were able to squash all of @1e-to changes into two separate commits retaining her name as commit's author, one for C-API and one for Python part. My review changes were also squashed into a separate commit. 

This should not been needed. If git branch is used to keep lots of WIP/backup snapshots, and the intent is to squash changes, or reorganize them in any other way, this should be done **by the author** before PR is opened for a review.

**Comment by oleksandr-pavlyk** [comment]
Good to go. Merging...

**Comment by oleksandr-pavlyk** [comment]
@diptorupd You need to approve, please.

**Review by diptorupd — APPROVED** [review]

**Comment by diptorupd** [comment]
Thanks @1e-to and @oleksandr-pavlyk

**Pull request merged**
