### PR TITLE
Omit test coverage

### PR DESCRIPTION
**Pull request by vlad-perevezentsev**
https://github.com/IntelPython/numba-dppy/pull/296#issuecomment-815291856

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
Please explain your decisions.

**Comment by vlad-perevezentsev** [comment]
Added a file with coverage configuration to the test section.
The **coveragerc** uses the [cython plugin](https://github.com/IntelPython/dpctl/blob/master/.coveragerc#L2), so the cython package was added to the test section.

**Comment by diptorupd** [comment]
The most recent build log reports this:

```
07:40:01
  Coverage statistics reporting failed
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.7/site-packages/teamcity_messages-1.25-py3.7.egg/teamcity/pytest_plugin.py", line 371, in pytest_terminal_summary
      self._report_coverage()
    File "$PREFIX/lib/python3.7/site-packages/teamcity_messages-1.25-py3.7.egg/teamcity/pytest_plugin.py", line 378, in _report_coverage
      from coverage.report import Reporter
  ImportError: cannot import name 'Reporter' from 'coverage.report' ($PREFIX/lib/python3.7/site-packages/coverage/report.py)
07:40:01
  ----------- coverage: platform linux, python 3.7.9-final-0 -----------
07:40:01
  Name                                                                                                                                                                                                                                                                                                                           Stmts   Miss Branch BrPart  Cover   Missing
07:40:01
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
07:40:01
  /localdisk/tools/tc/agent2/work/2cb6e2569bc46688/base/lib/python3.7/site-packages/conda_build/environ.py:426: UserWarning: The environment variable 'ONEAPI_ROOT' is being passed through with value /opt/intel/oneapi.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
07:40:01
  $PREFIX/lib/python3.7/site-packages/dpctl/__init__.py                       33      2      0      0    94%   73-75
07:40:01
    UserWarning
07:40:01
  $PREFIX/lib/python3.7/site-packages/dpctl/_version.py                        4      0      0      0   100%
07:40:01
  $PREFIX/lib/python3.7/site-packages/dpctl/dptensor/__init__.py               2      0      0      0   100%
07:40:01
  /localdisk/tools/tc/agent2/work/2cb6e2569bc46688/base/lib/python3.7/site-packages/conda_build/environ.py:418: UserWarning: The environment variable 'WHEELS_OUTPUT_FOLDER' is undefined.
07:40:01
  $PREFIX/lib/python3.7/site-packages/dpctl/dptensor/numpy_usm_shared.py     181     61     76     10    61%   45-46, 63, 67-78, 90, 117-118, 126-146, 174-175, 183, 186-200, 213-225, 240, 260, 264, 280-284, 288, 299, 317-319
07:40:01
  $PREFIX/lib/python3.7/site-packages/dpctl/enum_types.py                     17      0      0      0   100%
07:40:01
  $PREFIX/lib/python3.7/site-packages/dpctl/memory/__init__.py                 4      0      0      0   100%
07:40:01
  $PREFIX/lib/python3.7/site-packages/dpctl/program/__init__.py                4      0      0      0   100%
07:40:01
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
07:40:01
  TOTAL                                                                                                                                                                                                                                                                                                                            245     63     76     10    69%
07:40:01
```

I see the error about failing to import `Reporter` and no Cython coverage.

**Comment by diptorupd** [comment]
@vlad-perevezentsev @PokhodenkoSA I am closing this PR as we have coverage generation and reporting setup via a Github CI and coveralls.io. We do not have to add it to our Teamcity CI.

**Pull request closed without merging**
