### PR TITLE
Implements ``dpctl.tensor.clip``

### PR DESCRIPTION
**Pull request by ndgrigorian**
This pull request implements the function ``clip``, for clipping elements of an array to a range.
Clip permits both Python scalar and ``dpctl.tensor.usm_ndarray`` arguments for its ``min`` and ``max`` arguments.

An example of the new functionality:
```
In [1]: import dpctl.tensor as dpt, numpy as np

In [2]: x = dpt.arange(-2, 8, dtype="i4")

In [3]: dpt.clip(x, 0, 5)
Out[3]: usm_ndarray([0, 0, 0, 1, 2, 3, 4, 5, 5, 5], dtype=int32)
```

- [X] Have you provided a meaningful PR description?
- [X] Have you added a test, reproducer or referred to an issue with a reproducer?
- [X] Have you tested your changes locally for CPU and GPU devices?
- [X] Have you made sure that new changes do not introduce compiler warnings?
- [X] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
Encountered `TypeError`:

```
In [1]: import dpctl, dpctl.tensor as dpt, dpctl.utils as du

In [2]: x = dpt.arange(10)

In [3]: dpt.clip(x, 0, 10)
Out[3]: usm_ndarray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]: dpt.clip(x, 0, 5)
Out[4]: usm_ndarray([0, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [5]: dpt.clip(x, 0, dpt.inf)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
```

**Comment by ndgrigorian** [comment]
> Encountered `TypeError`:
> 
> ```
> In [1]: import dpctl, dpctl.tensor as dpt, dpctl.utils as du
> 
> In [2]: x = dpt.arange(10)
> 
> In [3]: dpt.clip(x, 0, 10)
> Out[3]: usm_ndarray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
> 
> In [4]: dpt.clip(x, 0, 5)
> Out[4]: usm_ndarray([0, 1, 2, 3, 4, 5, 5, 5, 5, 5])
> 
> In [5]: dpt.clip(x, 0, dpt.inf)
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> ```

This is currently the expected behavior, as the output is expected to be the same type as the input, and a float can't be cast to int.

**Comment by antonwolfy** [comment]
Checked with existing dpnp tests around `clip` and all of them are passed.

**Comment by oleksandr-pavlyk** [comment]
@ndgrigorian I think `ValueError` makes more sense in the example `dpt.bitwise_and(dpt.arange(10, dtype="i8"), dpt.inf)` as well. Thanks for bringing this up @ndgrigorian

**Comment by ndgrigorian** [comment]
> @ndgrigorian I think `ValueError` makes more sense in the example `dpt.bitwise_and(dpt.arange(10, dtype="i8"), dpt.inf)` as well. Thanks for bringing this up @ndgrigorian

Making this change was more breaking than expected for elementwise functions. It will belong in a separate PR, as it will have to touch a lot of tests and unary functions. There seem to also be other cases of inappropriate dtype -> TypeError throughout the project. It may make sense to change those as well.

For now, that work is done on just clip. The PR is ready for review.

**Review by oleksandr-pavlyk — APPROVED** [review]

**Pull request merged**
