### PR TITLE
Added a test that retrieved DPCPP compiled kernel and submits them via DPCTLQueue_SubmitRange

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
This does not presently work with coverage turned on due to LLVM version discrepancy between IGC and DPC++.

So the test is excluded for the build with coverage.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
Even though, logically, the ``sycl::kernel`` produced by ``dpcpp_kernel::get_fill_kernel`` has been given all the arguments that command group function object lambda would capture by reference, removing those from `DPCTLQueue_SubmitRange` results in an incorrect result (test fails).

Thus, duplicating these captured values via `set_args` appears needed. Perhaps this is to be expected, as the captured values are captured on the host side and must still be sent over to the device.

**Comment by oleksandr-pavlyk** [comment]
@diptorupd I have added tests for `DCPTLQueue_SubmitNDRange`. Expanded tests for `int`, `unsigned int`, `float` and `double`.

**Comment by oleksandr-pavlyk** [comment]
To fix the "generate-coverage" workflow it sufficies to remove linking to `dpcpp_kernels` static library.

The error is

```
[100%] Linking CXX executable dpctl_c_api_tests
error: Linking COMDATs named '__profd_dpcpp_kernels.cpp__ZN7__spirvL16initGlobalOffsetILi1EN2cl4sycl2idILi1EEEEET0_v': noduplicates has been violated!
dpcpp: error: sycl-link command failed with exit code 1 (use -v to see invocation)
```
 
@diptorupd Is there another way to fix it?

**Comment by oleksandr-pavlyk** [comment]
Failures on Linux are due to OpenCL runtime packages being unavailable on PyPI due to limitation on the size of published packages.

So this can be merged.

**Comment by diptorupd** [comment]
Merging to master as TeamCity CI fails due to `dpcpp_cpp_rt` package not being there on `pypi`.

**Review by diptorupd — APPROVED** [review]
Merging to master as TeamCity CI fails due to dpcpp_cpp_rt package not being there on pypi.

**Pull request merged**
