### PR TITLE
Implement take_along_axis function per Python Array API

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
The function is planned for Python Array API 2024.12 specification.

- [x] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to an issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [x] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Review by antonwolfy — COMMENTED** [review]
I've opened a PR to reuse the new dpctl function in [dpnp-1969](https://github.com/IntelPython/dpnp/pull/1969). The existing and new dpnp tests are passed with that dpctl PR locally.

**Comment by ndgrigorian** [comment]
@oleksandr-pavlyk 
I am going to try to take a look at this today.

One thing that I did realize, though: would it make sense to add `put_along_axis` as an inverse function? Array API obviously won't yet due to mutation issues, but we already have `put`, it seems like a good idea, maybe for a separate PR.

**Comment by oleksandr-pavlyk** [comment]
> One thing that I did realize, though: would it make sense to add `put_along_axis` as an inverse function? 

Yes, makes total sense. Let's do it in a separate PR though.

**Review by ndgrigorian — APPROVED** [review]
I've tested the branch out and it works, this LGTM.

Thank you @oleksandr-pavlyk !

**Pull request merged**
