### PR TITLE
Fix for incorrect result in reduction over axis=0

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Closes gh-1391

The specialized reduce_over_axis0 kernel should be called if both src/dst are F-contiguous, or when src is F-contig, and dst is C-contig but 1D (usually it is also F-contig in this case though).

- [x] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to an issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by ndgrigorian** [comment]
For me, building this branch gives a compiler warning

```
[84/89] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/sum_reductions.cpp.o
/home/ngrigori/dpctl/dpctl/tensor/libtensor/source/sum_reductions.cpp:222:35: warning: '&&' within '||' [-Wlogical-op-parentheses]
                 (is_dst_c_contig && dst_nd == 1 || dst.is_f_contiguous()))
```

**Comment by oleksandr-pavlyk** [comment]
> For me, building this branch gives a compiler warning
> 
> ```
> [84/89] Building CXX object dpctl/tensor/CMakeFiles/_tensor_impl.dir/libtensor/source/sum_reductions.cpp.o
> /home/ngrigori/dpctl/dpctl/tensor/libtensor/source/sum_reductions.cpp:222:35: warning: '&&' within '||' [-Wlogical-op-parentheses]
>                  (is_dst_c_contig && dst_nd == 1 || dst.is_f_contiguous()))
> ```

Thank you @ndgrigorian . I have added the parenthesis and the warning is gone for me.

**Review by antonwolfy — APPROVED** [review]
dpnp tests are passing now. Thank you @oleksandr-pavlyk !

**Review by ndgrigorian — APPROVED** [review]
Compiler warning is gone and it resolves the issue

**Pull request merged**
