### PR TITLE
Closes gh-1114 and gh-1116

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Closes gh-1114 and closes gh-1116.

A pass through doc-strings of dpctl.tensor functions and classes to improve rendering of the documentation and to expand docstring.

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?

### CODE REVIEW

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Found few left over issues: `reshape`, `from_dlpack` still have the `->` in the summary.

**Comment by diptorupd** [comment]
> @oleksandr-pavlyk Found few left over issues: `reshape`, `from_dlpack` still have the `->` in the summary.

It is a Sphinx issue IMO. The header of the detail section looks so much better with the `->` and it even auto links to the `usm_ndarray` doc. The summary is butchered up.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Can you please check the following function in our `generate_rst.py`: https://github.com/IntelPython/dpctl/blob/8f828f24ada9829ed4d9d5dc56e6d7f39dd9ac3c/docs/generate_rst.py#L378?

Maybe we need to fix the logic here and the `->` do not need to be removed from the signature in the docstring. Having the arrows generates much better detailed sections, and the butchered summary seems to be our doing.

**Comment by oleksandr-pavlyk** [comment]
> @oleksandr-pavlyk Can you please check the following function in our `generate_rst.py`:
> 
> https://github.com/IntelPython/dpctl/blob/8f828f24ada9829ed4d9d5dc56e6d7f39dd9ac3c/docs/generate_rst.py#L378
> 
> Maybe we need to fix the logic here and the `->` do not need to be removed from the signature in the docstring. Having the arrows generates much better detailed sections, and the butchered summary is in fact our doing.

I think we should be using Python's typing support in `dpctl.tensor` functions for IDE to pick up arrows and more details. 
It does not belong to the docstrings.

**Review by diptorupd — APPROVED** [review]

**Pull request merged**
