### PR TITLE
Fix gh-1769 - setting shape by a scalar

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
This PR resolves gh-1769

shape setter now accepts integer values.

- [x] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to an issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [x] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Review by ndgrigorian — COMMENTED** [review]
Does not work for -1, where NumPy does

```
In [2]: x = dpt.arange(100, dtype="i4")

In [3]: x.shape = -1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 x.shape = -1

File ~/repos/dpctl/dpctl/tensor/_usmarray.pyx:592, in dpctl.tensor._usmarray.usm_ndarray.shape.__set__()
    590 size = shape_to_elem_count(self.nd_, self.shape_)
    591 if not np.prod(new_shape) == size:
--> 592     raise TypeError(
    593         f"Can not reshape array of size {self.size} into {new_shape}"
    594     )

TypeError: Can not reshape array of size 100 into (-1,)
```

**Comment by oleksandr-pavlyk** [comment]
I added a docstring to document limitations of `usm_ndarray.shape` setter. The intent was never to match NumPy, although it is certainly possible.

**Review by ndgrigorian — APPROVED** [review]
LGTM!

**Review by antonwolfy — APPROVED** [review]
The dpnp scope of tests passed with the change. Thank you @oleksandr-pavlyk

**Pull request merged**
