### PR TITLE
Start kernel_arg_type enums from 0

### PR DESCRIPTION
**Pull request by ZzEeKkAa**
Fixes https://github.com/IntelPython/numba-dpex/pull/1379 and https://github.com/IntelPython/dpctl/pull/1581 . Other enums must be revisited.

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
The change itself seems fine, did you test whether numerical value of enum members in Python actually changed values because of this change? Should tests be added to verify numerical values of different enum members?

**Comment by ZzEeKkAa** [comment]
I've tested in numba-dpex. Definitely we need to test this and other enums in following PRs.

**Comment by oleksandr-pavlyk** [comment]
I have pushed a change to reimplement `kernel_arg_type` class using Cython, to have hard binding with values of enum in C.

This change would drop coverage, and requires adding more tests, feel free to add those, otherwise I'd push changes to add more tests a bit later.

**Comment by ZzEeKkAa** [comment]
LGTM! Tested localy for dpex - it works!

**Review by diptorupd — APPROVED** [review]
Nice improvements, four years in the waiting!

**Pull request merged**
