### PR TITLE
Add black formatter for Python code

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
[black](https://github.com/psf/black) is "The Uncompromising Code Formatter".

- [x] Use the black badge in project's README.md for indicating the code style
- [x] Add GitHub Actions for black for check code style
- [x] Ignore versioneer.py because it is 3rd party file (see `pyproject.toml`)
- [x] Format all Python code with black (just `black .`)
- [x] Add ignoring revisions in blame so you can see meaningful blame info after global formatting commit
- [x] Update CONTRIBUTING.md for all developers to use black in everyday work

Usage is simple: `black .`

This PR should be merged, not squashed.

### CODE REVIEW

**Comment by diptorupd** [comment]
Black is good. The only thing about it that I do not like is the 88 char wide lines. But, I can live with it.

**Comment by PokhodenkoSA** [comment]
> Black is good. The only thing about it that I do not like is the 88 char wide lines. But, I can live with it.

Line width is configurable via `--line-length`.

**Comment by PokhodenkoSA** [comment]
Using this [instruction](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame) we can migrate and make git blame to show original authors for all lines of code.

**Comment by oleksandr-pavlyk** [comment]
I think it is best to run this tool after #93 is merged, to avoid creating extensive conflicts.

**Comment by PokhodenkoSA** [comment]
@oleksandr-pavlyk Thank you for your attention.
I have plan about it. This PR is only demonstration of `black` possibilities.
I will reformat all in one commit and will add this commit to special file which will be used for ignoring commits during git blame and history.

**Pull request merged**
