### PR TITLE
Replace sycl::free with sycl_free_noexcept

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Replace ``sycl::free`` with ``sycl_free_noexcept``.

Add implementation of ``dpctl::tensor::offset_utils::sycl_free_noexcept`` templated function that calls ``sycl::free`` from within try/catch. The exception is logged to ``std::cerr``, but otherwise ignored.

Replaced calls to `sycl::free` in `host_task` with use of ``sycl_free_noexcept``.

This change should improve stability of test suite run executed on CPU device due to a known issue.

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Review by ndgrigorian — COMMENTED** [review]
In general this is a good change, but `offset_utils` seems like an unintuitive place to put it. I'm not sure where else it would belong though...

**Comment by oleksandr-pavlyk** [comment]
@ndgrigorian Is `utils/sycl_utils.hpp` more appropriate?

**Comment by ndgrigorian** [comment]
> @ndgrigorian Is `utils/sycl_utils.hpp` more appropriate?

I think that makes more sense.

**Comment by oleksandr-pavlyk** [comment]
@ndgrigorian I created `sycl_alloc_utils.hpp` to house these utility functions, and deployed it everywhere.

**Review by ndgrigorian — APPROVED** [review]

**Pull request merged**
