### PR TITLE
Support filter selector

### PR DESCRIPTION
**Pull request by diptorupd**

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
@diptorupd Is this PR still relevant?

**Comment by diptorupd** [comment]
> @diptorupd Is this PR still relevant?

It still has C API changes to expose context constructors and some changes to the platform_interface. I will extract those out and open separate PRs and close this one.

**Comment by oleksandr-pavlyk** [comment]
> > @diptorupd Is this PR still relevant?
> 
> It still has C API changes to expose context constructors and some changes to the platform_interface. I will extract those out and open separate PRs and close this one.

This would be helpful. I thought of working on `dpctl.SyclContext` next. I did not realize the C-API is not there yet.

**Comment by oleksandr-pavlyk** [comment]
I think this PR is now ready to retire :)

**Comment by diptorupd** [comment]
The last bit of CMake changes are now in #319. Closing (sigh!). What an epic PR that helped launch a "thousand" other PRs, but alas itself never reached master.

**Pull request closed without merging**
