### PR TITLE
Resolve deprecation warnings when building Cython examples

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
This PR adds `conda list` of the build environment to help understand the origin of compiler warnings in CI which are not reproducible locally.

**Edit**:

This PR resolves the issue by upgrading building system for Cython examples to use scikit-build.
CMake ensures that header files from the correct location are used. 

---

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] Have you checked performance impact of proposed changes?
- [ ] Have you added documentation for your changes, if necessary?
- [ ] Have you added your changes to the changelog?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
The warnings in `test_examples_linux` step come from 

```
In file included from blackscholes/blackscholes.cpp:1325:
In file included from /usr/share/miniconda/envs/examples/include/python3.11/../sycl/sycl.hpp:25:
In file included from /usr/share/miniconda/envs/examples/include/python3.11/../sycl/detail/core.hpp:21:
In file included from /usr/share/miniconda/envs/examples/include/python3.11/../sycl/accessor.hpp:11:
```

The folder `$CONDA_PREFIX/include/python.311/../sycl` does not exist for me locally, since my DPC++ comes from system-wide installation.

**Comment by oleksandr-pavlyk** [comment]
The immediate reason is that `intel-sycl-rt` package seems to include SYCL headers:

```
$ grep -r "sycl.hpp" $CONDA_PREFIX/conda-meta/
/localdisk/work/opavlyk/mamba/envs/test_examples/conda-meta/intel-sycl-rt-2025.0.4-intel_1519.json:    "include/sycl/CL/sycl.hpp",
```

Compiler finds these header files instead of those packages in the compiler itself in `build_env` environment.

**Comment by oleksandr-pavlyk** [comment]
I've changed build system for Cython examples over to scikit-build, and the warnings are now all gone.

**Comment by oleksandr-pavlyk** [comment]
Windows is failing due to a crash in one of conda's native extensions due to recent upgrade in miniforge, most likely updated version of mamba solver

**Review by ndgrigorian — APPROVED** [review]
Warnings are gone so this LGTM!

**Pull request merged**
