### PR TITLE
Rename all pxd and pyx filenames to start with _

### LINKED ISSUE #38: Cython modules should be renamed to have leading underscore
e.g. sycl_core.pyx to _sycl_core.pyx

### PR DESCRIPTION
**Pull request by diptorupd**
Closes #38

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
@diptorupd could you please resolve conflict?

**Comment by diptorupd** [comment]
@PokhodenkoSA I see the file names are already changed in master. Should I close this PR?

**Comment by PokhodenkoSA** [comment]
> @PokhodenkoSA I see the file names are already changed in master. Should I close this PR?

This PR has conflict. Maybe it will not add anything new when conflict will be resolved. Also in the issue #38 I describe that this renamings are useful to simplify build sctipt oin setup.py to use one command to build all Cython modules. Previously it was not possible because pyx file and final Cython module should have different names.

**Comment by PokhodenkoSA** [comment]
We can close it and create a new Issue for improving setup.py.

**Comment by diptorupd** [comment]
@PokhodenkoSA I have rebased it on top of master. Can be squash and merged now.

**Review by oleksandr-pavlyk — APPROVED** [review]

**Pull request closed without merging**
