### PR TITLE
Remove OpenCL interface

### PR DESCRIPTION
**Pull request by 1e-to**
This PR closes https://github.com/IntelPython/dpctl/issues/106

### CODE REVIEW

**Review by diptorupd — COMMENTED** [review]
cffi is no longer needed once ocldrv is removed, so meta.yaml should also be changed. Apart from that looks fine. Please make sure CI passes on both Windows and Linux.

**Review by PokhodenkoSA — APPROVED** [review]
As CI passed last time it LGTM.
I expect some things are not cleared but I can not list all it now.
I will merge if CI pass now.

**Comment by PokhodenkoSA** [comment]
I would like CHANGE_LOG to be updated too.

**Comment by diptorupd** [comment]
I tested it locally and things looked ok. Tested both `$scripts/build_for_develop.sh` and `conda build conda-recipe`.

**Pull request merged**
