### PR TITLE
Fix warnings in building libDPPLSyclInterface

### LINKED ISSUE #144: Fix all warnings
It is hard to see problems if there are many warnings during compilation of C++ and Cython modules.

### PR DESCRIPTION
**Pull request by diptorupd**
Fixes #144

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
Did you mean to push `` backends/warning.out``?

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Currently we are getting a flood of warning about the `tp_print` deprecation when we build our extensions. I looked up and these changes relate to [PEP 0590](https://www.python.org/dev/peps/pep-0590/) (also refer to https://bugs.python.org/issue37250, https://github.com/cython/cython/issues/2976, https://github.com/cython/cython/commit/f10a0a391edef10bd37095af87f521808cb362f7).

Based on what I see Cython should only include the `tp_print` member for when `#if PY_VERSION_HEX < 0x030800B1` is satisfied. I am using Python 3.8.5 and still see this warning. 

So, the question is how is the `PY_VERSION_HEX` set by Cython?

There are ways to work around the warning, e.g., https://github.com/openvinotoolkit/openvino/pull/2684/files that we can try. Any thoughts?

**Comment by oleksandr-pavlyk** [comment]
Cython does not set `PY_VERSION_HEX`. It comes from `Python.h`. 

Cython may be generating different C/C++ sources based on that value, but Cython does change it AFAIK.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I think this can be merged. It fixes all the warnings in the C++ code.

**Review by oleksandr-pavlyk — APPROVED** [review]

**Comment by diptorupd** [comment]
Merging after testing locally on Windows.

**Pull request merged**
