### PR TITLE
Remove USE_SYCL_FOR_COMPLEX_TYPES

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Always use SYCL namespace functions. Also replaced some std namespace functions with corresponding sycl namespace functions.

- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [x] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [x] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Comment by ndgrigorian** [comment]
Tested build with CUDA and it built successfully, so this LGTM.

Since I had to add pre-commit changes, can @antonwolfy or @vtavana please take a look at the changes and review this PR?

I still see some uses of `std::sin`, `std::cos`, etc. but I think these can be replaced in a follow-up PR.

**Comment by oleksandr-pavlyk** [comment]
The last commit, although green in CI, no longer build for NVPTX64 target, crashing during build of `cumulative_logsumexp.cpp` file.

It is best to report this to the attention of compiler engineers as a standalone reproducer and revert the culprit.

**Comment by ndgrigorian** [comment]
> The last commit, although green in CI, no longer build for NVPTX64 target, crashing during build of `cumulative_logsumexp.cpp` file.
> 
> It is best to report this to the attention of compiler engineers as a standalone reproducer and revert the culprit.
> 
> Crash log

Culprit appears to be `sycl::log1p`. I will revert the change to use `sycl::log1p` before this is merged, among other `std` function replacements.

**Review by ndgrigorian — APPROVED** [review]
With `sycl::log1p` to `std::log1p` change for `logaddexp` and remaining `std` functions changed, CUDA builds and tests seem to pass. I think the PR is ready.

**Review by antonwolfy — APPROVED** [review]
@ndgrigorian, `dpnp` tests passed with these changes without any new issue.

**Pull request merged**
