### PR TITLE
Optimized in-place operators for rows and matrices

### PR DESCRIPTION
**Pull request by ndgrigorian**
This PR significant improves the performance of in-place operations between C-contiguous rows and C-contiguous matrices by implementing a variant kernel similar to that which is used for standard binary operations.

- [X] Have you provided a meaningful PR description?
- [X] Have you added a test, reproducer or referred to an issue with a reproducer?
- [X] Have you tested your changes locally for CPU and GPU devices?
- [X] Have you made sure that new changes do not introduce compiler warnings?
- [X] Have you checked performance impact of proposed changes?
- [ ] If this PR is a work in progress, are you opening the PR as a draft?

### CODE REVIEW

**Review by vtavana — COMMENTED** [review]
I also noticed that, for instance, in `add.hpp` we define `class add_strided_strided_kernel` on line 221 which can be changed to `class add_strided_kernel` (obviously its usage on line 239 should also be modified). It is the same for all binary functions, so you may want to modify all of them in this PR.

**Review by npolina4 — DISMISSED** [review]
Thanks!

**Review by vtavana — DISMISSED** [review]
Thank you @ndgrigorian

**Review by vlad-perevezentsev — APPROVED** [review]
LGTM!
Thank you @ndgrigorian

**Review by vtavana — APPROVED** [review]

**Pull request merged**
