### PR TITLE
Sphinx and Doxygen documentation

### PR DESCRIPTION
**Pull request by diptorupd**
Adds an initial infrastructure to generate API documentation. Documentation generation works fine locally. Tried publishing them on gh-pages with not so great results.

I think Sphix+breathe+exhale+doxygen works much nicer than raw doxygen. Although, some information that is on doxygen is not showing up in sphinx using exhale and breathe.

Checkout [xtensor documentation](https://xtensor.readthedocs.io/en/latest/index.html) to see a more polished example than what I have managed to do thus far using breathe and exhale.

### CODE REVIEW

**Comment by diptorupd** [comment]
Pushed the static pages to gh-pages. You can see them rendered here [https://intelpython.github.io/dpctl/](https://intelpython.github.io/dpctl/). Somehow they render incorrectly.

**Comment by oleksandr-pavlyk** [comment]
Trying to compile with `build_for_develop`, I encountered:

```
CMake Error at CMakeLists.txt:192 (add_subdirectory):
  add_subdirectory given source "docs" which is not an existing directory.


-- Configuring incomplete, errors occurred!
```

**Comment by PokhodenkoSA** [comment]
> Pushed the static pages to gh-pages. You can see them rendered here https://intelpython.github.io/dpctl/. Somehow they render incorrectly.

I would like to propose URL like for SDC and add `-doc` suffix: https://intelpython.github.io/dpctl-doc/

@Alexander-Makaryev what are URLs for dpNP and daal4py?

**Comment by PokhodenkoSA** [comment]
Resolved merge conflict:
1. Formatted with black - master is black formatted
2. Merged with master

**Comment by PokhodenkoSA** [comment]
I have fixed incorrect rendering. Just created .nojekyll file. See this commit https://github.com/IntelPython/dpctl/commit/99e7f9bd32b9aa54c8187542a877195865d3dcf8

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Can you review the PR once more? I have fixed the CMakeLists.txt issue you found. I will like to merge this as the first step to making generating docs easier.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Actually let me move the changes to `backends\CMakeLists.txt` and sycl_core.pyx out of the PR.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Can you please review the changes I made to the Cython files to add `__all__`? I will like to merge this PR as it makes generating docs much easier.

**Review by oleksandr-pavlyk — APPROVED** [review]
LGTM.

**Pull request merged**
