### PR TITLE
Feature/device manager

### LINKED ISSUE #146: SyclContext must have method to give list of devices
`ctx.get_sycl_devices()` should give a list of SyclDevice objects associated with this context.

This is Python equivalent to `cl::sycl::context::get_devices()`. See table 4.14 in the provisional 2020 standard, here is an excerpt:

`std::vector<device> get_devices() const` | Returns a std::vector containing all SYCLdevices that are associated with this SYCLcontext. The value returned must beequal to that returned by get_info<info::context::devices>().
-- | --

Moreover, there should be a way to query the Queue Manager for a queue that would be consistent with the given context.

### LINKED ISSUE #248: Functions for enumerating devices
It is not possible now to enumerate devices and provide particular device and backend for `dpctl.device_context`.

### LINKED ISSUE #313: dpctl shuold use a primary or default context per root device
SYCL context creation is an expensive operation and should be avoided if possible. For this reason, dpctl should cache a default or primary context per device and use that context for queue creation on that device.

### PR DESCRIPTION
**Pull request by diptorupd**
Closes #146
Closes #248
Closes #313 

Various improvements to device management.

- Implements a `_sycl_device_factory` module to easily get the list of available devices in Python from SYCL.
- Dpctl now creates a cache of devices and stores a context per device that may be reused to create queues for the device.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
This is not right:

```python
In [1]: import dpctl

In [2]: dpctl.SyclDevice("gpu")
Out[2]: <dpctl.SyclDevice at 0x7fd76edb44b0>

In [3]: dpctl.SyclQueue(dpctl.SyclDevice("gpu"))
Out[3]: <dpctl._sycl_queue.SyclQueue at 0x7fd7641299b0>

In [4]: Out[3].get_sycl_device() # UNEXPECTED: expecting to see SyclDevice, like in Out[2], but getting None

In [5]: !git status
On branch feature/device_selectors
Your branch is up to date with 'dipto/feature/device_selectors'.

nothing to commit, working tree clean

In [6]: !git log -1 --format=%H
28022afb8df19f46a7e488677dfb6f13c988c802
```

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Needs more work. Something I did wrong results in `get_devices()` always returning all devices. I will look at it tomorrow, if you beat me to it and spot the issue let me know.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I think this is good to go. Unfortunately the PR became way too huge than I had intended it to be, but will be great if you take a pass before we merge.

**Review by oleksandr-pavlyk — APPROVED** [review]
Commits from this PR are also included in `feature/queue_manager_v2`.

**Pull request merged**
